/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

sequenceable OHOS.myseq;

interface test.IFoo {
    sharedptr<myseq> sharedptr_seq_func([in] sharedptr<myseq> inParam, [inout] sharedptr<myseq> inoutParam, [out] sharedptr<myseq> outParam);
    uniqueptr<myseq> uniqueptr_seq_func([in] uniqueptr<myseq> inParam, [inout] uniqueptr<myseq> inoutParam, [out] uniqueptr<myseq> outParam);
    sptr<myseq> sptr_seq_func([in] sptr<myseq> inParam, [inout] sptr<myseq> inoutParam, [out] sptr<myseq> outParam);
    null_sharedptr<myseq> nullsharedptr_seq_func([in] null_sharedptr<myseq> inParam, [inout] null_sharedptr<myseq> inoutParam, [out] null_sharedptr<myseq> outParam);
    null_uniqueptr<myseq> nulluniqueptr_seq_func([in] null_uniqueptr<myseq> inParam, [inout] null_uniqueptr<myseq> inoutParam, [out] null_uniqueptr<myseq> outParam);
    null_sptr<myseq> nullsptr_seq_func([in] null_sptr<myseq> inParam, [inout] null_sptr<myseq> inoutParam, [out] null_sptr<myseq> outParam);
}
