/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

sequenceable OHOS.MySeq;

interface OHOS.IFooPtr {
    sharedptr<MySeq> sharedptr_seq_func([in] sharedptr<MySeq> inParam, [inout] sharedptr<MySeq> inoutParam, [out] sharedptr<MySeq> outParam);
    uniqueptr<MySeq> uniqueptr_seq_func([in] uniqueptr<MySeq> inParam, [inout] uniqueptr<MySeq> inoutParam, [out] uniqueptr<MySeq> outParam);
    sptr<MySeq> sptr_seq_func([in] sptr<MySeq> inParam, [inout] sptr<MySeq> inoutParam, [out] sptr<MySeq> outParam);
}