/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

sequenceable  IncludeDir.Test..test.myseq;
sequenceable  IncludeDir...myseq2;
interface  IncludeDir.Test..test.myinterface;
interface  IncludeDir...myinterface2;

interface test.IFoo {
    void seq_test_func([in] myseq inParam, [out] myseq outParam, [inout] myseq inoutParam);
    void seq_test_func2([in] myseq2 inParam, [out] myseq2 outParam, [inout] myseq2 inoutParam);
    void interface_test_func([in] myinterface2 inParam, [out] myinterface2 outParam, [inout] myinterface2 inoutParam);
    void interface_test_func2([in] myinterface2 inParam, [out] myinterface2 outParam, [inout] myinterface2 inoutParam);
}
