/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

interface test.IFoo {
    [ipcincapacity 0] void func1();
    [ipcoutcapacity 0] void func2();
    [ipcincapacity 131072] void func3();
    [ipcoutcapacity 131072] void func4();
    [ipcincapacity 0, ipcoutcapacity 0] void func5();
    [ipcincapacity 131072, ipcoutcapacity 131072] void func6();
    [ipcincapacity 131071, ipcoutcapacity 131072] void func7();
    [ipcincapacity 131072, ipcoutcapacity 131071] void func8();
    [cacheable 100, oneway, ipccode 10, ipcincapacity 262144, ipcoutcapacity 1048576] void func9();
    [ipcincapacity] void func10();
    [ipcoutcapacity ] void func11();
    [ipcincapacity , ipcoutcapacity] void func12();
    [ipcincapacity abc123] void func13();
    [ipcoutcapacity a456bc] void func14();
    [ipcincapacity abc, ipcoutcapacity 0x1234] void func15();
    [ipcincapacity 1, ipcincapacity 2] void func16();
    [ipcoutcapacity 1, ipcoutcapacity 2] void func17();
}
