/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos.hdi.foo.v1_0;

import ohos.hdi.foo.v1_0.IFooCallback;
import ohos.hdi.foo.v1_0.Types;

interface IFooExt {
    TestFunc10([in] Ashmem inData, [out] Ashmem outData);
    TestFunc11([in] NativeBuffer inData, [out] NativeBuffer outData);
    TestFunc12([in] Pointer inData, [out] Pointer outData);
    TestFunc13([in] Map<String, String> inData, [out] Map<String, String> outData);
    TestFunc14([in] SharedMemQueue<unsigned char> inData, [out] SharedMemQueue<unsigned char> outData);
    [oneway] TestFunc15([in] unsigned char inData, [in] unsigned char outData);
    [oneway]  TestFunc16([in] unsigned int inData, [in] unsigned char outData);
    TestFunc17([in] unsigned short inData, [out] unsigned int outData);
    TestFunc18([in] unsigned long inData, [out] unsigned long outData);
    TestFunc19([in] struct FooInfo inData, [out] enum AudioPortPin outData);
    TestFunc20([in] struct AudioSceneDescriptor inData, [out] union SceneDesc outData);
}