/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

interface idl.OHOS.IFoo {
	[cacheable 100, oneway]void test001([in] int param1);
	[oneway, cacheable 0]void test002([in] double param1);
	[cacheable 0]void test005([in] short param1, [out] double param2);
	[cacheable 2]void test005([in] int param1, [out] int param2);
}