/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import ICustom;
import ICustomCopy;

[callback] interface OHOS.callback.IFoocallback {
    void void_test_func();
    FEnum enum_test_func([in] FEnum inParam, [out] FEnum outParam, [inout] FEnum inoutParam);
    FStruct struct_test_func([in] FStruct inParam, [out] FStruct outParam, [inout] FStruct inoutParam);
    FUnion union_test_func([in] FUnion inParam, [out] FUnion outParam, [inout] FUnion inoutParam);
    FUnionCopy union_test_func2([in] FUnion inParam, [out] FUnion outParam, [inout] FUnion inoutParam);
}