/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

sequenceable test.myseq;
interface test.myinterface;

interface test.IFooTs {
    [oneway] void void_test_func();
    [oneway] void bool_test_func([in] boolean inParam);
    [oneway] void byte_test_func([in] byte inParam);
    [oneway] void short_test_func([in] short inParam);
    [oneway] void int_test_func([in] int inParam);
    [oneway] void long_test_func([in] long inParam);
    [oneway] void string_test_func([in] String inParam);
    [oneway] void float_test_func([in] float inParam);
    [oneway] void double_test_func([in] double inParam);
    [oneway] void seq_test_func([in] myseq inParam);
    [oneway] void interface_test_func([in] myinterface inParam);
}
