/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
sequenceable test.myseq;
interface test.myinterface;

interface test.IFoo {
    Set<boolean> bool_test_func([in] Set<boolean> inParam, [out] Set<boolean> outParam, [inout] Set<boolean> inoutParam);
    Set<boolean> byte_test_func([in] Set<boolean> inParam, [out] Set<boolean> outParam, [inout] Set<boolean> inoutParam);
    Set<short> short_test_func([in] Set<short> inParam, [out] Set<short> outParam, [inout] Set<short> inoutParam);
    Set<int> int_test_func([in] Set<int> inParam, [out] Set<int> outParam, [inout] Set<int> inoutParam);
    Set<int[]> int_2_test_func([in] Set<int[]> inParam, [out] Set<int[]> outParam, [inout] Set<int[]> inoutParam);
    Set<int[][]> int_3_test_func([in] Set<int[][]> inParam, [out] Set<int[][]> outParam, [inout] Set<int[][]> inoutParam);
    Set<long> long_test_func([in] Set<long> inParam, [out] Set<long> outParam, [inout] Set<long> inoutParam);
    Set<String> string_test_func([in] Set<String> inParam, [out] Set<String> outParam, [inout] Set<String> inoutParam);
    Set<float> float_test_func([in] Set<float> inParam, [out] Set<float> outParam, [inout] Set<float> inoutParam);
    Set<double> double_test_func([in] Set<double> inParam, [out] Set<double> outParam, [inout] Set<double> inoutParam);
    Set<char> char_test_func([in] Set<char> inParam, [out] Set<char> outParam, [inout] Set<char> inoutParam);
    Set<Map<int, int[]>> map_test_func([in] Set<Map<int, int[]>> inParam, [out] Set<Map<int, int[]>> outParam, [inout] Set<Map<int, int[]>> inoutParam);
    Set<myseq> seq_test_func([in] Set<myseq> inParam, [out] Set<myseq> outParam, [inout] Set<myseq> inoutParam);
    Set<myinterface> interface_test_func([in] Set<myinterface> inParam, [out] Set<myinterface> outParam, [inout] Set<myinterface> inoutParam);
}
