/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

interface test.IFoo {
    // 有返回值
    [ipcincapacity 1] boolean bool_test_func([in] boolean inParam, [out] boolean outParam, [inout] boolean inoutParam);
    [ipcoutcapacity 1] byte byte_test_func([in] byte inParam, [out] byte outParam, [inout] byte inoutParam);
    [ipcincapacity 131071, ipcoutcapacity 131071] short short_test_func([in] short inParam, [out] short outParam, [inout] short inoutParam);
    [ipcoutcapacity 131071, ipcincapacity 131071] char char_test_func([in] char inParam, [out] char outParam, [inout] char inoutParam);
    [cacheable 100, oneway, ipccode 10, ipcincapacity 1, ipcoutcapacity 2] int int_test_func([in] int inParam);

    // 没返回值
    [ipcincapacity 1] void long_test_func([in] long inParam, [out] long outParam, [inout] long inoutParam);
    [ipcoutcapacity 1] void string_test_func([in] String inParam, [in] String outParam, [in] String inoutParam);
    [ipcincapacity 131071, ipcoutcapacity 131071] void float_test_func([in] float inParam, [in] float outParam, [in] float inoutParam);
    [ipcoutcapacity 131071, ipcincapacity 131071] FileDescriptor fd_test_func([in] FileDescriptor inParam, [out] FileDescriptor outParam, [inout] FileDescriptor inoutParam);
    [cacheable 200, oneway, ipccode 0x00ffffff, ipcincapacity 1, ipcoutcapacity 2] void double_test_func([in] double inParam);
}
